using System.Collections.Immutable;
using Microsoft.CodeAnalysis;

namespace WinUIShell.Generator;

internal static class AttributeGenerator
{
    private static readonly string s_surpressByNameAttributeName = "SurpressGeneratorByNameAttribute";
    private static readonly Dictionary<string, SurpressedClass> s_surpressedClasses = [];

    private class SurpressedClass
    {
        private readonly HashSet<string> _methodNames = [];

        public void AddMethodName(string methodName)
        {
            _ = _methodNames.Add(methodName);
        }

        public bool IsSurpressed(string methodName)
        {
            return _methodNames.Contains(methodName);
        }
    }

    public static string SurpressByNameAttributeFullName
    {
        get => $"WinUIShell.Generator.{s_surpressByNameAttributeName}";
    }

    public static void Generate(IncrementalGeneratorPostInitializationContext postInitContext)
    {
        var source = $$"""
                // <auto-generated/>

                namespace WinUIShell.Generator;

                [global::System.AttributeUsage(global::System.AttributeTargets.Method | global::System.AttributeTargets.Constructor, AllowMultiple = false)]
                internal sealed class {{s_surpressByNameAttributeName}} : global::System.Attribute
                {
                }
                """;
        postInitContext.AddSource("SurpressGeneratorByName.g.cs", source);
    }

    public static void InitSurpressDictionary(ImmutableArray<GeneratorAttributeSyntaxContext> surpressByNameAttributes)
    {
        foreach (GeneratorAttributeSyntaxContext attribute in surpressByNameAttributes)
        {
            if (attribute.TargetSymbol is not IMethodSymbol)
                continue;

            var className = attribute.TargetSymbol.ContainingType.ToString();
            var methodName = attribute.TargetSymbol.Name;

            if (!s_surpressedClasses.TryGetValue(className, out var surpressedClass))
            {
                surpressedClass = new();
                s_surpressedClasses.Add(className, surpressedClass);
            }
            surpressedClass.AddMethodName(methodName);
        }
    }

    public static void TermSurpressDictionary()
    {
        s_surpressedClasses.Clear();
    }

    public static bool IsSurpressed(MethodDef methodDef, bool isInterfaceImplExplicitImplementation = false)
    {
        var className = methodDef.ObjectDef.Type.GetName();
        var methodName = methodDef.GetName(isInterfaceImplExplicitImplementation);

        if (!s_surpressedClasses.TryGetValue(className, out var surpressedClass))
            return false;

        return surpressedClass.IsSurpressed(methodName);
    }

    public static bool IsSurpressed(EventDef eventDef, bool isInterfaceImplExplicitImplementation = false)
    {
        var className = eventDef.ObjectDef.Type.GetName();
        var methodName = eventDef.GetMethodFullName(isInterfaceImplExplicitImplementation);

        if (!s_surpressedClasses.TryGetValue(className, out var surpressedClass))
            return false;

        return surpressedClass.IsSurpressed(methodName);
    }

    public static bool IsConstructorSurpressed(string className)
    {
        var methodName = ".ctor";
        if (!s_surpressedClasses.TryGetValue(className, out var surpressedClass))
            return false;

        return surpressedClass.IsSurpressed(methodName);
    }
}
