using System.Text;
using Microsoft.CodeAnalysis;
using WinUIShell.Server;

namespace WinUIShell.Generator;

internal static class EnumGenerator
{
    public static void Generate(SourceProductionContext sourceProductionContext, Api api)
    {
        foreach (var enumDef in api.Enums)
        {
            StringBuilder sourceCode = new();

            var ns = Generator.GetTargetNamespace(enumDef.Namespace);

            _ = sourceCode.Append($$"""
                // <auto-generated/>

                namespace {{ns}};

                public enum {{enumDef.Name}} : {{enumDef.UnderlyingType}}
                {

                """);

            foreach (var item in enumDef.Entries)
            {
                _ = sourceCode.Append($"    {item.Name} = {item.Value},\r\n");
            }
            _ = sourceCode.Append("}\r\n");

            sourceProductionContext.AddSource($"WinUIShell.{enumDef.Namespace}.{enumDef.Name}.g.cs", sourceCode.ToString());
        }
    }

    public static void GenerateTypeMapping(SourceProductionContext sourceProductionContext, Api api)
    {
        StringBuilder sourceCode = new();

        _ = sourceCode.Append($$"""
            // <auto-generated/>
            #nullable enable

            namespace WinUIShell.Common;

            internal sealed class EnumTypeMapping : Singleton<EnumTypeMapping>
            {
                private readonly Dictionary<string, string> _map = [];

                public EnumTypeMapping()
                {
                    foreach (var map in _list)
                    {
                        _map.Add(map.Item1, map.Item2);
                        _map.Add(map.Item2, map.Item1);
                    }
                }

                public bool TryGetValue(string sourceEnumType, out string? targetEnumType)
                {
                    return _map.TryGetValue(sourceEnumType, out targetEnumType);
                }

                private readonly List<(string, string)> _list = [
            
            """);

        foreach (var enumDef in api.Enums)
        {
            var ns = Generator.GetTargetNamespace(enumDef.Namespace);
            _ = sourceCode.Append($"""
                        ("{ns}.{enumDef.Name}, WinUIShell", "{enumDef.FullName}"),

                """);
        }
        _ = sourceCode.Append("    ];\r\n}\r\n");

        sourceProductionContext.AddSource($"EnumTypeMapping.g.cs", sourceCode.ToString());
    }
}
