using Microsoft.CodeAnalysis;
using WinUIShell.Server;

namespace WinUIShell.Generator;

internal static class EnumGenerator
{
    public static void Generate(SourceProductionContext sourceProductionContext, Api api)
    {
        foreach (var enumDef in api.Enums)
        {
            var codeWriter = new CodeWriter();

            var ns = Generator.GetTargetNamespace(enumDef.Namespace);

            codeWriter.Append($$"""
                // <auto-generated/>

                namespace {{ns}};

                public enum {{enumDef.Name}} : global::System.{{enumDef.UnderlyingType}}
                {
                """);

            codeWriter.IncrementIndent();
            foreach (var item in enumDef.Entries)
            {
                codeWriter.Append($"{item.Name} = {item.Value},");
            }
            codeWriter.DecrementIndent();

            codeWriter.Append("}");

            sourceProductionContext.AddSource($"WinUIShell.{enumDef.Namespace}.{enumDef.Name}.g.cs", codeWriter.ToString());
        }
    }

    public static void GenerateTypeMapping(SourceProductionContext sourceProductionContext, Api api)
    {
        var codeWriter = new CodeWriter();

        codeWriter.Append($$"""
            // <auto-generated/>
            #nullable enable

            namespace WinUIShell.Common;

            internal sealed class EnumTypeMapping : Singleton<EnumTypeMapping>
            {
            """);

        codeWriter.IncrementIndent();
        codeWriter.Append($$"""
            private readonly Dictionary<string, string> _map = [];

            public EnumTypeMapping()
            {
                foreach (var map in _list)
                {
                    _map.Add(map.Item1, map.Item2);
                    _map.Add(map.Item2, map.Item1);
                }
            }

            public bool TryGetValue(string sourceEnumType, out string? targetEnumType)
            {
                return _map.TryGetValue(sourceEnumType, out targetEnumType);
            }

            private readonly List<(string, string)> _list = [
            """);

        codeWriter.IncrementIndent();
        foreach (var enumDef in api.Enums)
        {
            var ns = Generator.GetTargetNamespace(enumDef.Namespace);
            codeWriter.Append($"""
                ("{ns}.{enumDef.Name}, WinUIShell", "{enumDef.FullName}"),
                """);
        }
        codeWriter.DecrementIndent();

        codeWriter.Append("];");
        codeWriter.DecrementIndent();

        codeWriter.Append("}");

        sourceProductionContext.AddSource($"EnumTypeMapping.g.cs", codeWriter.ToString());
    }
}
