using Microsoft.CodeAnalysis;

namespace WinUIShell.Generator;

[Generator(LanguageNames.CSharp)]
public class Generator : IIncrementalGenerator
{
    private bool _field;
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput((postInitContext) =>
        {

        });

        var additionalTextProvider = context.AdditionalTextsProvider.Where((text) =>
        {
            return text.Path.EndsWith("Generator.json");
        });

        context.RegisterSourceOutput(additionalTextProvider, (sourceProductionContext, additionalText) =>
        {
            var sourceCode = $$"""
// <auto-generated/>

namespace WinUIShell;

public enum BackgroundSizing
{
    InnerBorderEdge,
    OuterBorderEdge
}

""";
            sourceProductionContext.AddSource("BackgroundSizing.g.cs", sourceCode);

        });
    }
}
