using System.Text;
using System.Xml.Serialization;
using Microsoft.CodeAnalysis;
using WinUIShell.Server;

namespace WinUIShell.Generator;

[Generator(LanguageNames.CSharp)]
public class Generator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput((postInitContext) =>
        {

        });

        var provider = context.AdditionalTextsProvider.Where((text) =>
        {
            return text.Path.EndsWith("Api.xml");
        }).Combine(context.AnalyzerConfigOptionsProvider);

        context.RegisterSourceOutput(provider, (sourceProductionContext, source) =>
        {
            var text = source.Left.GetText();
            if (text is null)
                return;

            var api = LoadApi(text.ToString());
            if (api is null)
                return;

            var configOptionsProvider = source.Right;
            if (configOptionsProvider.GlobalOptions.TryGetValue("build_property.WinUIShellGenerator_GenerateTypeMapping", out var generateTypeMapping))
            {
                GenerateEnumTypeMapping(sourceProductionContext, api);
            }
            else
            {
                GenerateEnums(sourceProductionContext, api);
                ObjectGenerator.Generate(sourceProductionContext, api);
            }
        });
    }

    private static Api LoadApi(string content)
    {
        var stringReader = new StringReader(content);
        var serializer = new XmlSerializer(typeof(Api));
        var api = (Api)serializer.Deserialize(stringReader);
        return api;
    }

    private static void GenerateEnumTypeMapping(SourceProductionContext sourceProductionContext, Api api)
    {
        StringBuilder sourceCode = new();

        _ = sourceCode.Append($$"""
            // <auto-generated/>
            #nullable enable

            namespace WinUIShell.Common;

            internal sealed class EnumTypeMapping : Singleton<EnumTypeMapping>
            {
                private readonly Dictionary<string, string> _map = [];

                public EnumTypeMapping()
                {
                    foreach (var map in _list)
                    {
                        _map.Add(map.Item1, map.Item2);
                        _map.Add(map.Item2, map.Item1);
                    }
                }

                public bool TryGetValue(string sourceEnumType, out string? targetEnumType)
                {
                    return _map.TryGetValue(sourceEnumType, out targetEnumType);
                }

                private readonly List<(string, string)> _list = [
            
            """);

        foreach (var enumDef in api.Enums)
        {
            var ns = GetTargetNamespace(enumDef.Namespace);
            _ = sourceCode.Append($"""
                        ("{ns}.{enumDef.Name}, WinUIShell", "{enumDef.FullName}"),

                """);
        }
        _ = sourceCode.Append("    ];\r\n}\r\n");

        sourceProductionContext.AddSource($"EnumTypeMapping.g.cs", sourceCode.ToString());
    }

    private static void GenerateEnums(SourceProductionContext sourceProductionContext, Api api)
    {
        foreach (var enumDef in api.Enums)
        {
            StringBuilder sourceCode = new();

            var ns = GetTargetNamespace(enumDef.Namespace);

            _ = sourceCode.Append($$"""
                // <auto-generated/>

                namespace {{ns}};

                public enum {{enumDef.Name}} : {{enumDef.UnderlyingType}}
                {

                """);

            foreach (var item in enumDef.Entries)
            {
                _ = sourceCode.Append($"    {item.Name} = {item.Value},\r\n");
            }
            _ = sourceCode.Append("}\r\n");

            sourceProductionContext.AddSource($"WinUIShell.{enumDef.Namespace}.{enumDef.Name}.g.cs", sourceCode.ToString());
        }
    }

    internal static string GetTargetNamespace(string serverNamespace)
    {
        return serverNamespace == "WinUIShell.Server" ? "WinUIShell" : $"WinUIShell.{serverNamespace}";
    }
}
