using System.Text;
using WinUIShell.Server;

namespace WinUIShell.Generator;

internal class ObjectDef
{
    private readonly Api.ObjectDef _apiObjectDef;
    private readonly TypeDef? _baseType;

    private readonly List<TypeDef> _interfaces = [];
    private readonly List<PropertyDef> _staticProperties = [];
    private readonly List<PropertyDef> _instanceProperties = [];
    private readonly List<MethodDef> _constructors = [];
    private readonly List<MethodDef> _staticMethods = [];
    private readonly List<MethodDef> _instanceMethods = [];

    public TypeDef Type { get; }

    public ObjectDef(Api.ObjectDef apiObjectDef)
    {
        _apiObjectDef = apiObjectDef;
        Type = new TypeDef(_apiObjectDef.Type);
        if (_apiObjectDef.BaseType is not null)
        {
            _baseType = new TypeDef(_apiObjectDef.BaseType);
        }

        foreach (var interfaceType in _apiObjectDef.Interfaces)
        {
            _interfaces.Add(new TypeDef(interfaceType));
        }
        foreach (var property in _apiObjectDef.StaticProperties)
        {
            _staticProperties.Add(new PropertyDef(property, this, MemberDefType.Static));
        }
        foreach (var property in _apiObjectDef.InstanceProperties)
        {
            _instanceProperties.Add(new PropertyDef(property, this, MemberDefType.Instance));
        }
        foreach (var constructor in _apiObjectDef.Constructors)
        {
            _constructors.Add(new MethodDef(constructor, this, MemberDefType.Constructor));
        }
        foreach (var method in _apiObjectDef.StaticMethods)
        {
            _staticMethods.Add(new MethodDef(method, this, MemberDefType.Static));
        }
        foreach (var method in _apiObjectDef.InstanceMethods)
        {
            _instanceMethods.Add(new MethodDef(method, this, MemberDefType.Instance));
        }
    }

    public bool IsSupported()
    {
        return Type.IsSupported() && !Type.IsSystemInterface;
    }

    public string GetSourceCodeFileName()
    {
        return $"WinUIShell.{_apiObjectDef.Namespace}.{_apiObjectDef.Name}.g.cs";
    }

    public string Generate()
    {
        StringBuilder sourceCode = new();

        var ns = Generator.GetTargetNamespace(_apiObjectDef.Namespace);

        _ = sourceCode.Append($$"""
                // <auto-generated/>
                #nullable enable

                using WinUIShell;
                using WinUIShell.Common;

                namespace {{ns}};


                """);

        if (Type.IsInterface)
        {
            GenerateInterface(sourceCode);
        }
        else
        {
            GenerateClass(sourceCode);
        }

        return sourceCode.ToString();
    }

    private void GenerateInterface(StringBuilder sourceCode)
    {
        string genericArgumentsExpression = Type.GetGenericArgumentsExpression();
        StringBuilder baseTypeExpression = new();
        foreach (var interfaceType in _interfaces)
        {
            if (interfaceType.IsSupported())
            {
                if (baseTypeExpression.Length == 0)
                {
                    _ = baseTypeExpression.Append(" : ");
                }
                else
                {
                    _ = baseTypeExpression.Append(", ");
                }
                _ = baseTypeExpression.Append(interfaceType.GetName());
            }
        }

        _ = sourceCode.Append($$"""
            public interface {{_apiObjectDef.Name}}{{genericArgumentsExpression}}{{baseTypeExpression}}
            {
            """);

        foreach (var method in _constructors)
        {
            if (!method.IsSupported())
                continue;

            _ = sourceCode.Append($$"""

                    {{method.GetConstructorSignatureExpression(_apiObjectDef.Name)}}

                """);
        }

        foreach (var property in _staticProperties)
        {
            if (!property.IsSupported())
                continue;

            _ = sourceCode.Append($$"""

                    {{property.GetSignatureExpression()}}
                    {

                """);

            if (property.CanRead)
            {
                _ = sourceCode.Append($$"""
                            get;

                    """);
            }

            if (property.CanWrite)
            {
                _ = sourceCode.Append($$"""
                            set;

                    """);
            }

            _ = sourceCode.Append("    }\r\n");
        }

        foreach (var property in _instanceProperties)
        {
            if (!property.IsSupported())
                continue;

            _ = sourceCode.Append($$"""

                    {{property.GetSignatureExpression()}}
                    {

                """);

            if (property.CanRead)
            {
                _ = sourceCode.Append($$"""
                            get;

                    """);
            }

            if (property.CanWrite)
            {
                _ = sourceCode.Append($$"""
                            set;

                    """);
            }

            _ = sourceCode.Append("    }\r\n");
        }

        foreach (var method in _staticMethods)
        {
            if (!method.IsSupported())
                continue;

            _ = sourceCode.Append($$"""

                    {{method.GetSignatureExpression()}};

                """);
        }

        foreach (var method in _instanceMethods)
        {
            if (!method.IsSupported())
                continue;

            _ = sourceCode.Append($$"""

                    {{method.GetSignatureExpression()}};

                """);
        }
        _ = sourceCode.Append("}\r\n");
    }

    private void GenerateClass(StringBuilder sourceCode)
    {
        string genericArgumentsExpression = Type.GetGenericArgumentsExpression();

        StringBuilder baseTypeExpression = new(" : WinUIShellObject");
        if (_baseType is not null && _baseType.IsSupported())
        {
            _ = baseTypeExpression.Append($", {_baseType.GetName()}");
        }
        foreach (var interfaceType in _interfaces)
        {
            if (interfaceType.IsSupported())
            {
                _ = baseTypeExpression.Append($", {interfaceType.GetName()}");
            }
        }

        _ = sourceCode.Append($$"""
            public class {{_apiObjectDef.Name}}{{genericArgumentsExpression}}{{baseTypeExpression}}
            {
                internal {{_apiObjectDef.Name}}(ObjectId id)
                    : base(id)
                {
                }

            """);


        foreach (var method in _constructors)
        {
            if (!method.IsSupported())
                continue;

            _ = sourceCode.Append($$"""

                    {{method.GetConstructorSignatureExpression(_apiObjectDef.Name)}}
                    {
                        Id = CommandClient.Get().CreateObject(
                            ObjectTypeMapping.Get().GetTargetTypeName<{{_apiObjectDef.Name}}>(),
                            this{{method.GetArgumentsExpression()}});
                    }

                """);
        }

        foreach (var property in _staticProperties)
        {
            if (!property.IsSupported())
                continue;

            _ = sourceCode.Append($$"""

                    {{property.GetSignatureExpression()}}
                    {

                """);

            if (property.CanRead)
            {
                _ = sourceCode.Append($$"""
                            get => PropertyAccessor.GetStatic<{{property.Type.GetName()}}>(
                                ObjectTypeMapping.Get().GetTargetTypeName<{{_apiObjectDef.Name}}>(),
                                nameof({{property.Name}})){{(property.Type.IsNullable ? "" : "!")}};

                    """);
            }

            if (property.CanWrite)
            {
                _ = sourceCode.Append($$"""
                            set => PropertyAccessor.SetStatic(
                                ObjectTypeMapping.Get().GetTargetTypeName<{{_apiObjectDef.Name}}>(),
                                nameof({{property.Name}}),
                                value);

                    """);
            }

            _ = sourceCode.Append("    }\r\n");
        }

        foreach (var property in _instanceProperties)
        {
            if (!property.IsSupported())
                continue;

            _ = sourceCode.Append($$"""

                    {{property.GetSignatureExpression()}}
                    {

                """);

            if (property.CanRead)
            {
                _ = sourceCode.Append($$"""
                            get => PropertyAccessor.Get<{{property.Type.GetName()}}>(Id, nameof({{property.Name}})){{(property.Type.IsNullable ? "" : "!")}};

                    """);
            }

            if (property.CanWrite)
            {
                _ = sourceCode.Append($$"""
                            set => PropertyAccessor.Set(Id, nameof({{property.Name}}), {{property.Type.GetValueExpression()}});

                    """);
            }

            _ = sourceCode.Append("    }\r\n");
        }

        foreach (var method in _staticMethods)
        {
            if (!method.IsSupported())
                continue;

            var returnType = method.ReturnType!;
            if (returnType.IsVoid)
            {
                _ = sourceCode.Append($$"""

                        {{method.GetSignatureExpression()}}
                        {
                            CommandClient.Get().InvokeStaticMethod(
                                ObjectTypeMapping.Get().GetTargetTypeName<{{_apiObjectDef.Name}}>(),
                                nameof({{method.GetName()}}){{method.GetArgumentsExpression()}});
                        }

                    """);
            }
            else
            {
                _ = sourceCode.Append($$"""

                        {{method.GetSignatureExpression()}}
                        {
                            return CommandClient.Get().InvokeStaticMethodAndGetResult<{{returnType.GetName()}}>(
                                ObjectTypeMapping.Get().GetTargetTypeName<{{_apiObjectDef.Name}}>(),
                                nameof({{method.GetName()}}){{method.GetArgumentsExpression()}}){{(returnType.IsNullable ? "" : "!")}};
                        }

                    """);
            }
        }

        foreach (var method in _instanceMethods)
        {
            if (!method.IsSupported())
                continue;

            var returnType = method.ReturnType!;
            if (returnType.IsVoid)
            {
                _ = sourceCode.Append($$"""

                        {{method.GetSignatureExpression()}}
                        {
                            CommandClient.Get().InvokeMethod(
                                Id,
                                nameof({{method.GetName()}}){{method.GetArgumentsExpression()}});
                        }

                    """);
            }
            else
            {
                _ = sourceCode.Append($$"""

                        {{method.GetSignatureExpression()}}
                        {
                            return CommandClient.Get().InvokeMethodAndGetResult<{{returnType.GetName()}}>(
                                Id,
                                nameof({{method.GetName()}}){{method.GetArgumentsExpression()}}){{(returnType.IsNullable ? "" : "!")}};
                        }

                    """);
            }
        }

        _ = sourceCode.Append("}\r\n");
    }
}
