using System.Text;
using Microsoft.CodeAnalysis;
using WinUIShell.Server;

namespace WinUIShell.Generator;

internal static class ObjectGenerator
{
    public static void Generate(SourceProductionContext sourceProductionContext, Api api)
    {
        foreach (var objectDef in api.Objects)
        {
            StringBuilder sourceCode = new();

            var ns = Generator.GetTargetNamespace(objectDef.Namespace);

            _ = sourceCode.Append($$"""
                // <auto-generated/>
                #nullable enable

                using WinUIShell;
                using WinUIShell.Common;

                namespace {{ns}};

                public class {{objectDef.Name}} : WinUIShellObject
                {
                    internal {{objectDef.Name}}(ObjectId id)
                      : base(id)
                    {
                    }

                """);

            foreach (var constructor in objectDef.Constructors)
            {
                _ = sourceCode.Append($$"""

                        public {{objectDef.Name}}(
                    """);


                string commaSpace = "";
                foreach (var parameter in constructor.Parameters)
                {
                    var parameterType = new ArgumentType(parameter.Type);
                    _ = sourceCode.Append($"{commaSpace}{parameterType.GetTypeExpression()} {parameter.Name}");
                    commaSpace = ", ";
                }

                _ = sourceCode.Append($$"""
                    )
                        {
                            Id = CommandClient.Get().CreateObject(
                                ObjectTypeMapping.Get().GetTargetTypeName<{{objectDef.Name}}>(),
                                this
                    """);

                foreach (var parameter in constructor.Parameters)
                {
                    _ = sourceCode.Append($",\r\n            {parameter.Name}");
                }
                _ = sourceCode.Append($$"""
                    );
                        }

                    """);
            }

            foreach (var property in objectDef.StaticProperties)
            {
                var propertyType = new ArgumentType(property.Type);
                if (!propertyType.IsSupported)
                    continue;

                _ = sourceCode.Append($$"""

                        public static {{propertyType.GetTypeExpression()}} {{property.Name}}
                        {

                    """);

                if (property.CanRead)
                {
                    _ = sourceCode.Append($$"""
                                get => PropertyAccessor.GetStatic<{{propertyType.GetName()}}>(
                                    ObjectTypeMapping.Get().GetTargetTypeName<{{objectDef.Name}}>(),
                                    nameof({{property.Name}})){{(propertyType.IsNullable ? "" : "!")}};

                        """);
                }

                if (property.CanWrite)
                {
                    _ = sourceCode.Append($$"""
                                set => PropertyAccessor.SetStatic(
                                    ObjectTypeMapping.Get().GetTargetTypeName<{{objectDef.Name}}>(),
                                    nameof({{property.Name}}),
                                    value);

                        """);
                }

                _ = sourceCode.Append("    }\r\n");
            }

            foreach (var property in objectDef.InstanceProperties)
            {
                var propertyType = new ArgumentType(property.Type);
                if (!propertyType.IsSupported)
                    continue;

                _ = sourceCode.Append($$"""

                        public {{propertyType.GetTypeExpression()}} {{property.Name}}
                        {

                    """);

                if (property.CanRead)
                {
                    _ = sourceCode.Append($$"""
                                get => PropertyAccessor.Get<{{propertyType.GetName()}}>(Id, nameof({{property.Name}})){{(propertyType.IsNullable ? "" : "!")}};

                        """);
                }

                if (property.CanWrite)
                {
                    _ = sourceCode.Append($$"""
                                set => PropertyAccessor.Set(Id, nameof({{property.Name}}), {{propertyType.GetValueExpression()}});

                        """);
                }

                _ = sourceCode.Append("    }\r\n");
            }

            _ = sourceCode.Append("}\r\n");

            sourceProductionContext.AddSource($"WinUIShell.{objectDef.Namespace}.{objectDef.Name}.g.cs", sourceCode.ToString());
        }
    }
}
