using System.Text;
using Microsoft.CodeAnalysis;
using WinUIShell.Server;

namespace WinUIShell.Generator;

internal static class ObjectGenerator
{
    public static void Generate(SourceProductionContext sourceProductionContext, Api api)
    {
        foreach (var objectDef in api.Objects)
        {
            StringBuilder sourceCode = new();

            var ns = Generator.GetTargetNamespace(objectDef.Namespace);

            _ = sourceCode.Append($$"""
                // <auto-generated/>
                #nullable enable

                using WinUIShell;
                using WinUIShell.Common;

                namespace {{ns}};

                public class {{objectDef.Name}} : WinUIShellObject
                {
                    internal {{objectDef.Name}}(ObjectId id)
                      : base(id)
                    {
                    }

                """);

            foreach (var property in objectDef.StaticProperties)
            {
                var propertyType = new ArgumentType(property.Type);
                if (!propertyType.IsSupported)
                    continue;

                _ = sourceCode.Append($$"""

                        public static {{propertyType.Name}}{{(propertyType.IsNullable ? "?" : "")}} {{property.Name}}
                        {

                    """);

                if (property.CanRead)
                {
                    _ = sourceCode.Append($$"""
                                get => PropertyAccessor.GetStatic<{{propertyType.Name}}>(
                                    ObjectTypeMapping.Get().GetTargetTypeName<{{objectDef.Name}}>(),
                                    nameof({{property.Name}})){{(propertyType.IsNullable ? "" : "!")}};

                        """);
                }

                if (property.CanWrite)
                {
                    _ = sourceCode.Append($$"""
                                set => PropertyAccessor.SetStatic(
                                    ObjectTypeMapping.Get().GetTargetTypeName<{{objectDef.Name}}>(),
                                    nameof({{property.Name}}),
                                    value);

                        """);
                }

                _ = sourceCode.Append("    }\r\n");
            }

            foreach (var property in objectDef.InstanceProperties)
            {
                var propertyType = new ArgumentType(property.Type);
                if (!propertyType.IsSupported)
                    continue;

                _ = sourceCode.Append($$"""

                        public {{propertyType.Name}}{{(propertyType.IsNullable ? "?" : "")}} {{property.Name}}
                        {

                    """);

                if (property.CanRead)
                {
                    _ = sourceCode.Append($$"""
                                get => PropertyAccessor.Get<{{propertyType.Name}}>(Id, nameof({{property.Name}})){{(propertyType.IsNullable ? "" : "!")}};

                        """);
                }

                if (property.CanWrite)
                {
                    _ = sourceCode.Append($$"""
                                set => PropertyAccessor.Set(Id, nameof({{property.Name}}), {{GenerateValueString(propertyType)}});

                        """);
                }

                _ = sourceCode.Append("    }\r\n");
            }

            _ = sourceCode.Append("}\r\n");

            sourceProductionContext.AddSource($"WinUIShell.{objectDef.Namespace}.{objectDef.Name}.g.cs", sourceCode.ToString());
        }
    }

    private static string GenerateValueString(ArgumentType argumentType)
    {
        if (argumentType.IsPrimitiveType)
        {
            return "value";
        }
        else
        if (argumentType.IsObject)
        {
            return "(value is WinUIShellObject v ? v.Id : value)";
        }
        else
        {
            return "value?.Id";
        }
    }

}
