using Microsoft.CodeAnalysis;
using WinUIShell.Server;

namespace WinUIShell.Generator;

internal static class ObjectGenerator
{
    private static readonly Dictionary<string, ObjectDef> _objectDefs = [];

    public static void Generate(SourceProductionContext sourceProductionContext, Api api)
    {
        CreateObjectDefMap(api);

        foreach (var keyValuePair in _objectDefs)
        {
            ObjectDef objectDef = keyValuePair.Value;
            string filename = objectDef.GetSourceCodeFileName();
            string sourceCode = objectDef.Generate();
            sourceProductionContext.AddSource(filename, sourceCode);
        }

        DestroyObjectDefMap();
    }

    private static void CreateObjectDefMap(Api api)
    {
        foreach (var apiObjectDef in api.Objects)
        {
            ObjectDef objectDef = new(apiObjectDef);
            if (!objectDef.IsSupported())
                continue;

            var uniqueName = objectDef.Type.GetUniqueName();
            if (_objectDefs.ContainsKey(uniqueName))
            {
                throw new InvalidOperationException($"Duplicate object found: {uniqueName}");
            }
            _objectDefs[uniqueName] = objectDef;
        }
    }

    private static void DestroyObjectDefMap()
    {
        _objectDefs.Clear();
    }

    public static ObjectDef? GetObjectDef(TypeDef typeDef)
    {
        var uniqueName = typeDef.GetUniqueName();
        if (_objectDefs.TryGetValue(uniqueName, out var objectDef))
        {
            return objectDef;
        }
        return null;
    }

    public static void GenerateTypeMapping(SourceProductionContext sourceProductionContext, Api api)
    {
        var codeWriter = new CodeWriter();

        codeWriter.Append($$"""
            // <auto-generated/>
            #nullable enable

            namespace WinUIShell.Common;

            public sealed class ObjectTypeMapping : Singleton<ObjectTypeMapping>
            {
            """);

        codeWriter.IncrementIndent();
        codeWriter.Append($$"""
            private readonly Dictionary<string, string> _map = [];

            public ObjectTypeMapping()
            {
                foreach (var map in _list)
                {
                    _map.Add(map.Item1, map.Item2);
                    _map.Add(map.Item2, map.Item1);
                }
            }

            internal bool TryGetValue(string sourceTypeName, out string? targetTypeName)
            {
                return _map.TryGetValue(sourceTypeName, out targetTypeName);
            }

            public string GetTargetTypeName<T>()
            {
                Type type = typeof(T);
                var typeName = type.FullName;
                var assemblyName = type.Assembly.GetName().Name;
                var sourceTypeName = $"{typeName}, {assemblyName}";

                if (type == typeof(object))
                {
                    return sourceTypeName;
                }

                _ = TryGetValue(sourceTypeName, out string? targetTypeName);
                if (targetTypeName is null)
                {
                    throw new InvalidOperationException($"Object type mapping not found for [{sourceTypeName}].");
                }
                return targetTypeName;
            }

            private readonly List<(string, string)> _list = [
            """);

        codeWriter.IncrementIndent();
        foreach (var apiObjectDef in api.Objects)
        {
            ObjectDef objectDef = new(apiObjectDef);
            if (!objectDef.IsSupported())
                continue;

            var ns = Generator.GetTargetNamespace(apiObjectDef.Namespace);
            var genericArgumentCount = apiObjectDef.Type.GenericTypeArguments.Count;
            string genericSuffix = (genericArgumentCount > 0) ? $"`{genericArgumentCount}" : "";

            codeWriter.Append($"""
                ("{ns}.{apiObjectDef.Name}{genericSuffix}, WinUIShell", "{apiObjectDef.FullName}"),
                """);
        }
        codeWriter.DecrementIndent();

        codeWriter.Append("];");
        codeWriter.DecrementIndent();

        codeWriter.Append("}");

        sourceProductionContext.AddSource($"ObjectTypeMapping.g.cs", codeWriter.ToString());
    }
}
