using System.Text;
using WinUIShell.Server;

namespace WinUIShell.Generator;

internal class ObjectDef
{
    private readonly Api.ObjectDef _apiObjectDef;
    private readonly TypeDef? _baseType;
    private readonly ObjectDef? _parentObjectDef;

    private readonly List<TypeDef> _interfaces = [];
    private readonly List<PropertyDef> _staticProperties = [];
    private readonly List<PropertyDef> _instanceProperties = [];
    private readonly List<MethodDef> _constructors = [];
    private readonly List<MethodDef> _staticMethods = [];
    private readonly List<MethodDef> _instanceMethods = [];
    private readonly List<ObjectDef> _nestedObjects = [];

    public TypeDef Type { get; }

    public ObjectDef(Api.ObjectDef apiObjectDef, ObjectDef? parentObjectDef = null)
    {
        _apiObjectDef = apiObjectDef;
        _parentObjectDef = parentObjectDef;

        Type = new TypeDef(_apiObjectDef.Type);
        if (_apiObjectDef.BaseType is not null)
        {
            _baseType = new TypeDef(_apiObjectDef.BaseType);
        }

        foreach (var interfaceType in _apiObjectDef.Interfaces)
        {
            _interfaces.Add(new TypeDef(interfaceType));
        }
        foreach (var property in _apiObjectDef.StaticProperties)
        {
            _staticProperties.Add(new PropertyDef(property, this, MemberDefType.Static));
        }
        foreach (var property in _apiObjectDef.InstanceProperties)
        {
            _instanceProperties.Add(new PropertyDef(property, this, MemberDefType.Instance));
        }
        foreach (var constructor in _apiObjectDef.Constructors)
        {
            _constructors.Add(new MethodDef(constructor, this, MemberDefType.Constructor));
        }
        foreach (var method in _apiObjectDef.StaticMethods)
        {
            _staticMethods.Add(new MethodDef(method, this, MemberDefType.Static));
        }
        foreach (var method in _apiObjectDef.InstanceMethods)
        {
            _instanceMethods.Add(new MethodDef(method, this, MemberDefType.Instance));
        }
        foreach (var nestedType in _apiObjectDef.NestedTypes)
        {
            _nestedObjects.Add(new ObjectDef(nestedType, this));
        }
    }

    public bool IsSupported()
    {
        return Type.IsSupported() && !Type.IsRpcSupportedType && !Type.IsObject && !Type.IsSystemInterface;
    }

    public string GetSourceCodeFileName()
    {
        var fullName = _apiObjectDef.FullName.Split(',')[0];
        return $"WinUIShell.{fullName}.g.cs";
    }

    public string Generate()
    {
        var codeWriter = new CodeWriter();

        var ns = Generator.GetTargetNamespace(_apiObjectDef.Namespace);
        codeWriter.Append($$"""
            // <auto-generated/>
            #nullable enable

            using WinUIShell;
            using WinUIShell.Common;

            namespace {{ns}};
            """);

        Generate(codeWriter);
        return codeWriter.ToString();
    }

    public void Generate(CodeWriter codeWriter)
    {
        if (Type.IsInterface)
        {
            GenerateInterface(codeWriter);
        }
        else
        {
            GenerateClass(codeWriter);
        }
    }

    private void GenerateInterface(CodeWriter codeWriter)
    {
        string genericArgumentsExpression = Type.GetGenericArgumentsExpression(_parentObjectDef?.Type.GenericArguments);
        StringBuilder baseTypeExpression = new();
        foreach (var interfaceType in _interfaces)
        {
            if (interfaceType.IsSupported())
            {
                if (baseTypeExpression.Length == 0)
                {
                    _ = baseTypeExpression.Append(" : ");
                }
                else
                {
                    _ = baseTypeExpression.Append(", ");
                }
                _ = baseTypeExpression.Append(interfaceType.GetName());
            }
        }

        codeWriter.Append($$"""
            public interface {{_apiObjectDef.Name}}{{genericArgumentsExpression}}{{baseTypeExpression}}
            {
            """);
        codeWriter.IncrementIndent();

        foreach (var method in _constructors)
        {
            if (!method.IsSupported())
                continue;

            codeWriter.Append($$"""
                {{method.GetConstructorSignatureExpression(_apiObjectDef.Name)}}
                """);
        }

        foreach (var property in _staticProperties)
        {
            if (!property.IsSupported())
                continue;

            codeWriter.Append($$"""
                {{property.GetSignatureExpression()}}
                {
                """);
            codeWriter.IncrementIndent();

            if (property.CanRead)
            {
                codeWriter.Append($$"""
                    get;
                    """);
            }

            if (property.CanWrite)
            {
                codeWriter.Append($$"""
                    set;
                    """);
            }

            codeWriter.DecrementIndent();
            codeWriter.Append("}");
        }

        foreach (var property in _instanceProperties)
        {
            if (!property.IsSupported())
                continue;

            codeWriter.Append($$"""
                {{property.GetSignatureExpression()}}
                {
                """);
            codeWriter.IncrementIndent();

            if (property.CanRead)
            {
                codeWriter.Append($$"""
                    get;
                    """);
            }

            if (property.CanWrite)
            {
                codeWriter.Append($$"""
                    set;
                    """);
            }

            codeWriter.DecrementIndent();
            codeWriter.Append("}");
        }

        foreach (var method in _staticMethods)
        {
            if (!method.IsSupported())
                continue;

            codeWriter.Append($$"""
                {{method.GetSignatureExpression()}};
                """);
        }

        foreach (var method in _instanceMethods)
        {
            if (!method.IsSupported())
                continue;

            codeWriter.Append($$"""
                {{method.GetSignatureExpression()}};
                """);
        }

        foreach (var nestedObject in _nestedObjects)
        {
            nestedObject.Generate(codeWriter);
        }

        codeWriter.DecrementIndent();
        codeWriter.Append("}");
    }

    private void GenerateClass(CodeWriter codeWriter)
    {
        string genericArgumentsExpression = Type.GetGenericArgumentsExpression(_parentObjectDef?.Type.GenericArguments);

        StringBuilder baseTypeExpression = new();
        if (_baseType is not null && _baseType.IsSupported())
        {
            _ = baseTypeExpression.Append($" : {_baseType.GetName()}");
        }
        else
        {
            _ = baseTypeExpression.Append($" : WinUIShellObject");
        }

        foreach (var interfaceType in _interfaces)
        {
            if (interfaceType.IsSupported())
            {
                _ = baseTypeExpression.Append($", {interfaceType.GetName()}");
            }
        }

        string abstractExpression = _apiObjectDef.Type.IsAbstract ? "abstract " : "";

        codeWriter.Append($$"""
            public {{abstractExpression}}class {{_apiObjectDef.Name}}{{genericArgumentsExpression}}{{baseTypeExpression}}
            {
            """);
        codeWriter.IncrementIndent();

        bool hasDefaultConstructor = false;
        foreach (var method in _constructors)
        {
            if (!method.IsSupported())
                continue;

            if (method.Parameters.Count == 0)
            {
                hasDefaultConstructor = true;
            }

            if (_apiObjectDef.Type.IsAbstract)
            {
                codeWriter.Append($$"""
                    {{method.GetConstructorSignatureExpression(_apiObjectDef.Name)}}
                    {
                    }
                    """);
            }
            else
            {
                codeWriter.Append($$"""
                    {{method.GetConstructorSignatureExpression(_apiObjectDef.Name)}}
                    {
                        Id = CommandClient.Get().CreateObject(
                            ObjectTypeMapping.Get().GetTargetTypeName<{{Type.GetName()}}>(),
                            this{{method.GetArgumentsExpression()}});
                    }
                    """);
            }
        }

        if (_apiObjectDef.Type.IsAbstract && !hasDefaultConstructor)
        {
            codeWriter.Append($$"""
            internal {{_apiObjectDef.Name}}()
            {
            }
            """);
        }

        codeWriter.Append($$"""
            internal {{_apiObjectDef.Name}}(ObjectId id)
                : base(id)
            {
            }
            """);

        foreach (var property in _staticProperties)
        {
            if (!property.IsSupported())
                continue;

            codeWriter.Append($$"""
                {{property.GetSignatureExpression()}}
                {
                """);
            codeWriter.IncrementIndent();

            if (property.CanRead)
            {
                if (property.IsAbstract)
                {
                    codeWriter.Append($$"""
                        get;
                        """);
                }
                else
                {
                    codeWriter.Append($$"""
                        get => PropertyAccessor.GetStatic<{{property.Type.GetName()}}>(
                            ObjectTypeMapping.Get().GetTargetTypeName<{{Type.GetName()}}>(),
                            nameof({{property.GetName()}})){{(property.Type.IsNullable ? "" : "!")}};
                        """);
                }
            }

            if (property.CanWrite)
            {
                if (property.IsAbstract)
                {
                    codeWriter.Append($$"""
                        set;
                        """);
                }
                else
                {
                    codeWriter.Append($$"""
                        set => PropertyAccessor.SetStatic(
                            ObjectTypeMapping.Get().GetTargetTypeName<{{Type.GetName()}}>(),
                            nameof({{property.GetName()}}),
                            value);
                        """);
                }
            }

            codeWriter.DecrementIndent();
            codeWriter.Append("}");
        }

        foreach (var property in _instanceProperties)
        {
            if (!property.IsSupported())
                continue;

            codeWriter.Append($$"""
                {{property.GetSignatureExpression()}}
                {
                """);
            codeWriter.IncrementIndent();

            if (property.CanRead)
            {
                if (property.IsAbstract)
                {
                    codeWriter.Append($$"""
                        get;
                        """);
                }
                else
                if (property.IsIndexer)
                {
                    codeWriter.Append($$"""
                        get => PropertyAccessor.GetIndexer<{{property.Type.GetName()}}>(Id{{property.GetIndexerArgumentsExpression()}}){{(property.Type.IsNullable ? "" : "!")}};
                        """);
                }
                else
                {
                    codeWriter.Append($$"""
                        get => PropertyAccessor.Get<{{property.Type.GetName()}}>(Id, nameof({{property.GetName()}})){{(property.Type.IsNullable ? "" : "!")}};
                        """);
                }
            }

            if (property.CanWrite)
            {
                if (property.IsAbstract)
                {
                    codeWriter.Append($$"""
                        set;
                        """);
                }
                else
                if (property.IsIndexer)
                {
                    codeWriter.Append($$"""
                        set => PropertyAccessor.SetIndexer(Id{{property.GetIndexerArgumentsExpression()}}, {{property.Type.GetValueExpression()}});
                        """);
                }
                else
                {
                    codeWriter.Append($$"""
                        set => PropertyAccessor.Set(Id, nameof({{property.GetName()}}), {{property.Type.GetValueExpression()}});
                        """);
                }
            }

            codeWriter.DecrementIndent();
            codeWriter.Append("}");
        }

        foreach (var method in _staticMethods)
        {
            if (!method.IsSupported())
                continue;

            var returnType = method.ReturnType!;
            if (method.IsAbstract)
            {
                codeWriter.Append($$"""
                    {{method.GetSignatureExpression()}};
                    """);
            }
            else
            if (returnType.IsVoid)
            {
                codeWriter.Append($$"""
                    {{method.GetSignatureExpression()}}
                    {
                        CommandClient.Get().InvokeStaticMethod(
                            ObjectTypeMapping.Get().GetTargetTypeName<{{Type.GetName()}}>(),
                            nameof({{method.GetName()}}){{method.GetArgumentsExpression()}});
                    }
                    """);
            }
            else
            {
                codeWriter.Append($$"""
                    {{method.GetSignatureExpression()}}
                    {
                        return CommandClient.Get().InvokeStaticMethodAndGetResult<{{returnType.GetName()}}>(
                            ObjectTypeMapping.Get().GetTargetTypeName<{{Type.GetName()}}>(),
                            nameof({{method.GetName()}}){{method.GetArgumentsExpression()}}){{(returnType.IsNullable ? "" : "!")}};
                    }
                    """);
            }
        }

        foreach (var method in _instanceMethods)
        {
            if (SpecializedMethodGenerator.Generate(codeWriter, method))
                continue;

            if (!method.IsSupported())
                continue;

            var returnType = method.ReturnType!;
            if (method.IsAbstract)
            {
                codeWriter.Append($$"""
                    {{method.GetSignatureExpression()}};
                    """);
            }
            else
            if (returnType.IsVoid)
            {
                codeWriter.Append($$"""
                    {{method.GetSignatureExpression()}}
                    {
                        CommandClient.Get().InvokeMethod(
                            Id,
                            nameof({{method.GetName()}}){{method.GetArgumentsExpression()}});
                    }
                    """);
            }
            else
            {
                codeWriter.Append($$"""
                    {{method.GetSignatureExpression()}}
                    {
                        return CommandClient.Get().InvokeMethodAndGetResult<{{returnType.GetName()}}>(
                            Id,
                            nameof({{method.GetName()}}){{method.GetArgumentsExpression()}}){{(returnType.IsNullable ? "" : "!")}};
                    }
                    """);
            }
        }

        foreach (var nestedObject in _nestedObjects)
        {
            nestedObject.Generate(codeWriter);
        }

        codeWriter.DecrementIndent();
        codeWriter.Append("}");
    }
}
