using System.Text;
using WinUIShell.Server;

namespace WinUIShell.Generator;

internal class ObjectDef
{
    private readonly Api.ObjectDef _apiObjectDef;
    private readonly TypeDef? _baseType;
    private readonly ObjectDef? _parentObjectDef;

    private readonly List<TypeDef> _interfaces = [];
    private readonly List<PropertyDef> _staticProperties = [];
    private readonly List<PropertyDef> _instanceProperties = [];
    private readonly List<MethodDef> _constructors = [];
    private readonly List<MethodDef> _staticMethods = [];
    private readonly List<MethodDef> _instanceMethods = [];
    private readonly List<ObjectDef> _nestedObjects = [];

    public TypeDef Type { get; }

    public ObjectDef(Api.ObjectDef apiObjectDef, ObjectDef? parentObjectDef = null)
    {
        _apiObjectDef = apiObjectDef;
        _parentObjectDef = parentObjectDef;

        Type = new TypeDef(_apiObjectDef.Type);
        if (_apiObjectDef.BaseType is not null)
        {
            _baseType = new TypeDef(_apiObjectDef.BaseType);
        }

        if (_apiObjectDef.Interfaces is not null)
        {
            foreach (var interfaceType in _apiObjectDef.Interfaces)
            {
                _interfaces.Add(new TypeDef(interfaceType));
            }
        }
        if (_apiObjectDef.StaticProperties is not null)
        {
            foreach (var property in _apiObjectDef.StaticProperties)
            {
                _staticProperties.Add(new PropertyDef(property, this, MemberDefType.Static));
            }
        }
        if (_apiObjectDef.InstanceProperties is not null)
        {
            foreach (var property in _apiObjectDef.InstanceProperties)
            {
                _instanceProperties.Add(new PropertyDef(property, this, MemberDefType.Instance));
            }
        }
        if (_apiObjectDef.Constructors is not null)
        {
            foreach (var constructor in _apiObjectDef.Constructors)
            {
                _constructors.Add(new MethodDef(constructor, this, MemberDefType.Constructor));
            }
        }
        if (_apiObjectDef.StaticMethods is not null)
        {
            foreach (var method in _apiObjectDef.StaticMethods)
            {
                _staticMethods.Add(new MethodDef(method, this, MemberDefType.Static));
            }
        }
        if (_apiObjectDef.InstanceMethods is not null)
        {
            foreach (var method in _apiObjectDef.InstanceMethods)
            {
                _instanceMethods.Add(new MethodDef(method, this, MemberDefType.Instance));
            }
        }
        if (_apiObjectDef.NestedTypes is not null)
        {
            foreach (var nestedType in _apiObjectDef.NestedTypes)
            {
                _nestedObjects.Add(new ObjectDef(nestedType, this));
            }
        }
    }

    public bool IsSupported()
    {
        return Type.IsSupported() && !Type.IsRpcSupportedType && !Type.IsObject;
    }

    public string GetSourceCodeFileName()
    {
        var fullName = _apiObjectDef.FullName.Split(',')[0];
        return $"WinUIShell.{fullName}.g.cs";
    }

    public string Generate()
    {
        var codeWriter = new CodeWriter();

        var ns = Generator.GetTargetNamespace(_apiObjectDef.Namespace);
        codeWriter.Append($$"""
            // <auto-generated/>
            #nullable enable

            using WinUIShell;
            using WinUIShell.Common;

            namespace {{ns}};
            """);

        Generate(codeWriter);
        return codeWriter.ToString();
    }

    public void Generate(CodeWriter codeWriter)
    {
        if (Type.IsInterface)
        {
            GenerateInterface(codeWriter);
        }
        else
        {
            GenerateClass(codeWriter);
        }
    }

    private void GenerateInterface(CodeWriter codeWriter)
    {
        string genericArgumentsExpression = Type.GetGenericArgumentsExpression(_parentObjectDef?.Type.GenericArguments);
        StringBuilder baseTypeExpression = new();
        foreach (var interfaceType in _interfaces)
        {
            if (interfaceType.IsSupported())
            {
                if (baseTypeExpression.Length == 0)
                {
                    _ = baseTypeExpression.Append(" : ");
                }
                else
                {
                    _ = baseTypeExpression.Append(", ");
                }
                _ = baseTypeExpression.Append(interfaceType.GetName());
            }
        }

        if (baseTypeExpression.Length == 0)
        {
            _ = baseTypeExpression.Append($" : IWinUIShellObject");
        }

        if (Type.IsSystemInterface)
        {
            _ = baseTypeExpression.Append($", {Type.GetSystemInterfaceName()}");
        }

        codeWriter.Append($$"""
            public interface {{_apiObjectDef.Name}}{{genericArgumentsExpression}}{{baseTypeExpression}}
            {
            """);

        if (!Type.IsSystemInterface)
        {
            codeWriter.IncrementIndent();

            foreach (var method in _constructors)
            {
                if (!method.IsSupported())
                    continue;

                codeWriter.Append($$"""
                    {{method.GetConstructorSignatureExpression(_apiObjectDef.Name)}}
                    """);
            }

            foreach (var property in _staticProperties)
            {
                if (!property.IsSupported())
                    continue;

                codeWriter.Append($$"""
                    {{property.GetSignatureExpression()}}
                    {
                    """);
                codeWriter.IncrementIndent();

                if (property.CanRead)
                {
                    codeWriter.Append($$"""
                        get;
                        """);
                }

                if (property.CanWrite)
                {
                    codeWriter.Append($$"""
                        set;
                        """);
                }

                codeWriter.DecrementIndent();
                codeWriter.Append("}");
            }

            foreach (var property in _instanceProperties)
            {
                if (!property.IsSupported())
                    continue;

                codeWriter.Append($$"""
                    {{property.GetSignatureExpression()}}
                    {
                    """);
                codeWriter.IncrementIndent();

                if (property.CanRead)
                {
                    codeWriter.Append($$"""
                        get;
                        """);
                }

                if (property.CanWrite)
                {
                    codeWriter.Append($$"""
                        set;
                        """);
                }

                codeWriter.DecrementIndent();
                codeWriter.Append("}");
            }

            foreach (var method in _staticMethods)
            {
                if (!method.IsSupported())
                    continue;

                codeWriter.Append($$"""
                    {{method.GetSignatureExpression()}};
                    """);
            }

            foreach (var method in _instanceMethods)
            {
                if (!method.IsSupported())
                    continue;

                codeWriter.Append($$"""
                    {{method.GetSignatureExpression()}};
                    """);
            }

            foreach (var nestedObject in _nestedObjects)
            {
                nestedObject.Generate(codeWriter);
            }

            codeWriter.DecrementIndent();
        }
        codeWriter.Append("}");
    }

    private void GenerateClass(CodeWriter codeWriter)
    {
        string genericArgumentsExpression = Type.GetGenericArgumentsExpression(_parentObjectDef?.Type.GenericArguments);

        StringBuilder baseTypeExpression = new();
        if (_baseType is not null && _baseType.IsSupported())
        {
            _ = baseTypeExpression.Append($" : {_baseType.GetName()}");
        }
        bool hasBaseType = baseTypeExpression.Length > 0;

        foreach (var interfaceType in _interfaces)
        {
            if (interfaceType.IsSupported())
            {
                if (baseTypeExpression.Length == 0)
                {
                    _ = baseTypeExpression.Append(" : ");
                }
                else
                {
                    _ = baseTypeExpression.Append(", ");
                }
                _ = baseTypeExpression.Append(interfaceType.GetName());
            }
        }

        if (baseTypeExpression.Length == 0)
        {
            _ = baseTypeExpression.Append($" : IWinUIShellObject");
        }

        string abstractExpression = _apiObjectDef.Type.IsAbstract ? "abstract " : "";

        codeWriter.Append($$"""
            public {{abstractExpression}}class {{_apiObjectDef.Name}}{{genericArgumentsExpression}}{{baseTypeExpression}}
            {
            """);
        codeWriter.IncrementIndent();

        if (!hasBaseType)
        {
            codeWriter.Append($$"""
                public ObjectId WinUIShellObjectId { get; protected set; } = new();
                """);
        }

        bool hasDefaultConstructor = false;
        foreach (var method in _constructors)
        {
            if (!method.IsSupported())
                continue;

            if (method.Parameters.Count == 0)
            {
                hasDefaultConstructor = true;
            }

            if (_apiObjectDef.Type.IsAbstract)
            {
                codeWriter.Append($$"""
                    {{method.GetConstructorSignatureExpression(_apiObjectDef.Name)}}
                    {
                    }
                    """);
            }
            else
            {
                codeWriter.Append($$"""
                    {{method.GetConstructorSignatureExpression(_apiObjectDef.Name)}}
                    {
                        WinUIShellObjectId = CommandClient.Get().CreateObject(
                            ObjectTypeMapping.Get().GetTargetTypeName<{{Type.GetName()}}>(),
                            this{{method.GetArgumentsExpression()}});
                    }
                    """);
            }
        }

        if (_apiObjectDef.Type.IsAbstract && !hasDefaultConstructor)
        {
            codeWriter.Append($$"""
                internal {{_apiObjectDef.Name}}()
                {
                }
                """);
        }

        if (hasBaseType)
        {
            codeWriter.Append($$"""
                internal {{_apiObjectDef.Name}}(ObjectId id)
                    : base(id)
                {
                }
                """);
        }
        else
        {
            codeWriter.Append($$"""
                internal {{_apiObjectDef.Name}}(ObjectId id)
                {
                    WinUIShellObjectId = id;
                }
                """);
        }

        foreach (var property in _staticProperties)
        {
            if (!property.IsSupported())
                continue;

            codeWriter.Append($$"""
                {{property.GetSignatureExpression()}}
                {
                """);
            codeWriter.IncrementIndent();

            if (property.CanRead)
            {
                if (property.IsAbstract)
                {
                    codeWriter.Append($$"""
                        get;
                        """);
                }
                else
                {
                    codeWriter.Append($$"""
                        get => PropertyAccessor.GetStatic<{{property.Type.GetName()}}>(
                            ObjectTypeMapping.Get().GetTargetTypeName<{{Type.GetName()}}>(),
                            nameof({{property.GetName()}})){{(property.Type.IsNullable ? "" : "!")}};
                        """);
                }
            }

            if (property.CanWrite)
            {
                if (property.IsAbstract)
                {
                    codeWriter.Append($$"""
                        set;
                        """);
                }
                else
                {
                    codeWriter.Append($$"""
                        set => PropertyAccessor.SetStatic(
                            ObjectTypeMapping.Get().GetTargetTypeName<{{Type.GetName()}}>(),
                            nameof({{property.GetName()}}),
                            value);
                        """);
                }
            }

            codeWriter.DecrementIndent();
            codeWriter.Append("}");
        }

        foreach (var property in _instanceProperties)
        {
            if (!property.IsSupported())
                continue;

            codeWriter.Append($$"""
                {{property.GetSignatureExpression()}}
                {
                """);
            codeWriter.IncrementIndent();

            if (property.CanRead)
            {
                if (property.IsAbstract)
                {
                    codeWriter.Append($$"""
                        get;
                        """);
                }
                else
                if (property.IsIndexer)
                {
                    codeWriter.Append($$"""
                        get => PropertyAccessor.GetIndexer<{{property.Type.GetName()}}>(WinUIShellObjectId{{property.GetIndexerArgumentsExpression()}}){{(property.Type.IsNullable ? "" : "!")}};
                        """);
                }
                else
                {
                    codeWriter.Append($$"""
                        get => PropertyAccessor.Get<{{property.Type.GetName()}}>(WinUIShellObjectId, nameof({{property.GetName()}})){{(property.Type.IsNullable ? "" : "!")}};
                        """);
                }
            }

            if (property.CanWrite)
            {
                if (property.IsAbstract)
                {
                    codeWriter.Append($$"""
                        set;
                        """);
                }
                else
                if (property.IsIndexer)
                {
                    codeWriter.Append($$"""
                        set => PropertyAccessor.SetIndexer(WinUIShellObjectId{{property.GetIndexerArgumentsExpression()}}, {{property.Type.GetValueExpression()}});
                        """);
                }
                else
                {
                    codeWriter.Append($$"""
                        set => PropertyAccessor.Set(WinUIShellObjectId, nameof({{property.GetName()}}), {{property.Type.GetValueExpression()}});
                        """);
                }
            }

            codeWriter.DecrementIndent();
            codeWriter.Append("}");
        }

        foreach (var method in _staticMethods)
        {
            if (!method.IsSupported())
                continue;

            var returnType = method.ReturnType!;
            if (method.IsAbstract)
            {
                codeWriter.Append($$"""
                    {{method.GetSignatureExpression()}};
                    """);
            }
            else
            if (returnType.IsVoid)
            {
                codeWriter.Append($$"""
                    {{method.GetSignatureExpression()}}
                    {
                        CommandClient.Get().InvokeStaticMethod(
                            ObjectTypeMapping.Get().GetTargetTypeName<{{Type.GetName()}}>(),
                            nameof({{method.GetName()}}){{method.GetArgumentsExpression()}});
                    }
                    """);
            }
            else
            {
                codeWriter.Append($$"""
                    {{method.GetSignatureExpression()}}
                    {
                        return CommandClient.Get().InvokeStaticMethodAndGetResult<{{returnType.GetName()}}>(
                            ObjectTypeMapping.Get().GetTargetTypeName<{{Type.GetName()}}>(),
                            nameof({{method.GetName()}}){{method.GetArgumentsExpression()}}){{(returnType.IsNullable ? "" : "!")}};
                    }
                    """);
            }
        }

        foreach (var method in _instanceMethods)
        {
            if (SpecializedMethodGenerator.Generate(codeWriter, method))
                continue;

            if (!method.IsSupported())
                continue;

            var returnType = method.ReturnType!;
            if (method.IsAbstract)
            {
                codeWriter.Append($$"""
                    {{method.GetSignatureExpression()}};
                    """);
            }
            else
            if (returnType.IsVoid)
            {
                codeWriter.Append($$"""
                    {{method.GetSignatureExpression()}}
                    {
                        CommandClient.Get().InvokeMethod(
                            WinUIShellObjectId,
                            nameof({{method.GetName()}}){{method.GetArgumentsExpression()}});
                    }
                    """);
            }
            else
            {
                codeWriter.Append($$"""
                    {{method.GetSignatureExpression()}}
                    {
                        return CommandClient.Get().InvokeMethodAndGetResult<{{returnType.GetName()}}>(
                            WinUIShellObjectId,
                            nameof({{method.GetName()}}){{method.GetArgumentsExpression()}}){{(returnType.IsNullable ? "" : "!")}};
                    }
                    """);
            }
        }

        foreach (var nestedObject in _nestedObjects)
        {
            nestedObject.Generate(codeWriter);
        }

        codeWriter.DecrementIndent();
        codeWriter.Append("}");
    }
}
